# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import voyage_pb2 as voyage__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voyage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoyageStub:
    """Same business capability as the HTTP API, exposed over gRPC.
    The servicer delegates to the exact same service layer (ai_service),
    so HTTP and RPC are two transports over one implementation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/voyage.Voyage/Ping',
                request_serializer=voyage__pb2.PingRequest.SerializeToString,
                response_deserializer=voyage__pb2.PingReply.FromString,
                _registered_method=True)
        self.Generate = channel.unary_unary(
                '/voyage.Voyage/Generate',
                request_serializer=voyage__pb2.GenerateRequest.SerializeToString,
                response_deserializer=voyage__pb2.GenerateReply.FromString,
                _registered_method=True)


class VoyageServicer:
    """Same business capability as the HTTP API, exposed over gRPC.
    The servicer delegates to the exact same service layer (ai_service),
    so HTTP and RPC are two transports over one implementation.
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoyageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=voyage__pb2.PingRequest.FromString,
                    response_serializer=voyage__pb2.PingReply.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=voyage__pb2.GenerateRequest.FromString,
                    response_serializer=voyage__pb2.GenerateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voyage.Voyage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voyage.Voyage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Voyage:
    """Same business capability as the HTTP API, exposed over gRPC.
    The servicer delegates to the exact same service layer (ai_service),
    so HTTP and RPC are two transports over one implementation.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voyage.Voyage/Ping',
            voyage__pb2.PingRequest.SerializeToString,
            voyage__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voyage.Voyage/Generate',
            voyage__pb2.GenerateRequest.SerializeToString,
            voyage__pb2.GenerateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
