# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voyage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'voyage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvoyage.proto\x12\x06voyage\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\"I\n\x0fGenerateRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x14\n\x0crequirements\x18\x03 \x01(\t\"F\n\rGenerateReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0eitinerary_json\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2t\n\x06Voyage\x12.\n\x04Ping\x12\x13.voyage.PingRequest\x1a\x11.voyage.PingReply\x12:\n\x08Generate\x12\x17.voyage.GenerateRequest\x1a\x15.voyage.GenerateReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voyage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=24
  _globals['_PINGREQUEST']._serialized_end=54
  _globals['_PINGREPLY']._serialized_start=56
  _globals['_PINGREPLY']._serialized_end=101
  _globals['_GENERATEREQUEST']._serialized_start=103
  _globals['_GENERATEREQUEST']._serialized_end=176
  _globals['_GENERATEREPLY']._serialized_start=178
  _globals['_GENERATEREPLY']._serialized_end=248
  _globals['_VOYAGE']._serialized_start=250
  _globals['_VOYAGE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
